### ISSUE TITLE
Catering for PV Systems with East/West Parallel Strings

### ISSUE THREAD

**Issue by spoonwzd** [BJReplay/PowerwallService#3]
My 7.08kW PV system actually consists of 2x 3.54kW systems distributed East & West (azimuth 130° & 310° respectively). They are presented as two separate strings connected in parallel to a 3.68kW PV inverter, so while my generation exceeds 3.68kW during periods of the day, I am ultimately limited by the capacity of the inverter.

While I am looking to replace my inverter with a larger (5kW) one in the near future, I believe my questions will still valid:

• How do I cater for this configuration with SolCast?
• Should PVSystemCapacity be defined as the total panel capacity, or at the inverter limit?

Thanks in advance :)

**Comment by BJReplay** [comment]
You presumably have a very flat generation curve through the day - that's not a bad system to have.  Given that the idea behind using Solcast is to work out how much **less** than ideal power you'll generate due to weather effects, so that you can pre-charge if needed, I think putting in your location, and a system capacity and average azimuth that generates a total forecast that matches what you actually get (e.g. on a clear day, so there's no cloud effect) is the best you can do (unless you want to grab the code and modify it to handle two forecasts for two (or more systems).

When your system is weather affected, the impact will be the same regardless of which string is generating more, so the solcast forecast should show lower power which will result in a lower forecast energy.

Capacity should be acheiveable capacity - so inverter limit for the moment while you are inverter limited.  I'd get in touch with the solcast team on their forum and ask them if they have plans for a multi-system API.

**Comment by AnthonyBe** [comment]
Re. Azimuth, with the more recent advent of 'optimised' PV installs using Enphase or SolarEdge optimizers, it is a lot more common to have banks of panels scattered across multiple roof faces, and thus multiple 'directions'.

I'm in the same boat (mix of NE and NNW facing panels) and simply very roughly averaged the capacity azimuth.

**Comment by spoonwzd** [comment]
@BJReplay Average azimuth is something I'd not thought of - thanks! I'll give it a try and see how it compares against my pvoutput stats over time.

**Comment by spoonwzd** [comment]
@AnthonyBe Yes that's exactly what I have - optimisers on my PV panels feeding a SolarEdge inverter. I'll average my azimuth :)
