### ISSUE TITLE
Logging only option?

### ISSUE THREAD

**Issue by AnthonyBe** [BJReplay/PowerwallService#6]
With Tesla now turning on the ToU shifting, I was wondering if you would consider having an option on your service to **only** perform the logging functions, i.e.

1. Log to local SQL server or Azure SQL Server
2. Log to local SQL server or Azure SQL Server and upload to PVOutput.org
3. Log to Power BI

without any manipulation of PW settings (i.e. let the native Tesla app now handle this function)

While I'm not entirely convinced Tesla's capability matches what you have now, let alone in the future, I am thinking ahead to when this does become a reality for some. That could be tomorrow, next week, or never :)

FYI, I'd like to do 2. and 3. from above :) I LOVE that you're into Power BI as well!!!

**Comment by BJReplay** [comment]
I hope that Tesla make the forecasting and control redundant, too.

Agree it needs to be an option.

Setting PWPeakConsumption to 0, PWMorningBuffer to 0 and PWOvernightLoad to 0 (possibly 1 - just in case setting to zero exposes a divide by zero) should result in no attempt to start charging in the mean time.

**Comment by AnthonyBe** [comment]
Cool - I'll give it a try and see what happens!

**Comment by AnthonyBe** [comment]
Oh, any chance you could provide your Power BI .pbix files to save having to completely re-create by hand? :)

.. or create a content pack? :P

**Comment by BJReplay** [comment]
Yeah, I've been trying to work out how to package the powerbi stuff - right now, I don't think I can package the definition of the streaming dataset (I could write a program but I don't think I can export an importable definition), and the dashboards were pulled together on the web platform rather than on the desktop (I'm not actually sure you can do it on the desktop at the moment given that it is dashboard based and beta), but I can probably put together instructions.  The creation by hand is actually really quick in any case - I talked a colleague through it on the phone screen sharing in 10 minutes.

Working on no control release now.

**Comment by BJReplay** [comment]
See https://github.com/BJReplay/PowerwallService/blob/master/PowerwallServiceAlpha0.9.9.0.zip
Release notes in ZIP

**Comment by AnthonyBe** [comment]
Yeah, after doing a little more poking around on Streaming datasets I realised the same; you can't build with PBI Desktop, it all has to be done in web console so no easy/obvious way to 'package' what you have built...
